name: flutter_second
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  carousel_slider: ^4.2.1 
  provider: ^6.1.2
  encrypt: ^5.0.0
  flutter_secure_storage: ^9.2.1
  flutter_dotenv: ^5.0.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: lib/assets/fonts/NotoSans-VariableFont_wdth,wght.ttf      
    - family: NotoSansRegular
      fonts:
        - asset: lib/assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansLight
      fonts:
        - asset: lib/assets/fonts/NotoSans-Light.ttf
          
  assets:
      - .env  